// This file is auto-generated by @hey-api/openapi-ts

export const HelloSyncActionsKeysSchema = {
    description: 'Lists all action keys as enum values',
    type: 'string',
    enum: ['set_message'],
    title: 'HelloSyncActionsKeys'
} as const;

export const HelloSyncActionsParamsSchema = {
    description: 'Maps each action keys to its parameters',
    properties: {
        set_message: {
            '$ref': '#/components/schemas/HelloSyncActionSetMessage'
        }
    },
    required: ['set_message'],
    title: 'HelloSyncActionsParams',
    type: 'object'
} as const;

export const HelloSyncTasksKeysSchema = {
    description: 'Lists all task keys as enum values',
    type: 'string',
    enum: [],
    title: 'HelloSyncTasksKeys'
} as const;

export const HelloSyncTasksParamsSchema = {
    description: 'Maps each task key to its parameters',
    properties: {},
    required: [],
    title: 'HelloSyncTasksParams',
    type: 'object'
} as const;

export const HelloSyncSchema = {
    properties: {
        message: {
            default: "hey what's up",
            title: 'Message',
            type: 'string'
        }
    },
    required: ['message'],
    title: 'HelloSync',
    type: 'object'
} as const;

export const HelloSyncActionSetMessageSchema = {
    properties: {
        message: {
            title: 'Message',
            type: 'string'
        }
    },
    required: ['message'],
    title: 'HelloSyncActionSetMessage',
    type: 'object'
} as const;
