// This file is auto-generated by @hey-api/openapi-ts

export const BackendStateActionsKeysSchema = {
    description: 'Lists all action keys as enum values',
    type: 'string',
    enum: ['add_channel'],
    title: 'BackendStateActionsKeys'
} as const;

export const BackendStateActionsParamsSchema = {
    description: 'Maps each action keys to its parameters',
    properties: {
        add_channel: {
            '$ref': '#/components/schemas/BackendStateActionAddChannel'
        }
    },
    required: ['add_channel'],
    title: 'BackendStateActionsParams',
    type: 'object'
} as const;

export const BackendStateTasksKeysSchema = {
    description: 'Lists all task keys as enum values',
    type: 'string',
    enum: [],
    title: 'BackendStateTasksKeys'
} as const;

export const BackendStateTasksParamsSchema = {
    description: 'Maps each task key to its parameters',
    properties: {},
    required: [],
    title: 'BackendStateTasksParams',
    type: 'object'
} as const;

export const BackendStateSchema = {
    properties: {
        channels: {
            default: [
                {
                    id: '123',
                    nickname: 'Channel 1',
                    handle: 'channel1',
                    description: 'Description 1',
                    avatar_url: 'https://p16-common-sign.tiktokcdn-us.com/tos-maliva-avt-0068/f611aa99e7db2b1f81ce145c7b063078~tplv-tiktokx-cropcenter:1080:1080.jpeg?dr=9640&refresh_token=cb4d1315&x-expires=1763413200&x-signature=tkYPKZGSeWlK%2BYxuvzFyhzRxR%2FI%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=81f88b70&idc=useast8',
                    stats: {
                        follower_count: 100,
                        following_count: 100,
                        heart_count: 100,
                        video_count: 100
                    }
                }
            ],
            items: {
                '$ref': '#/components/schemas/TiktokChannel'
            },
            title: 'Channels',
            type: 'array'
        },
        posts: {
            default: [
                {
                    id: '456',
                    title: 'Post 1',
                    description: 'Description 1',
                    url: 'https://www.tiktok.com/post1',
                    views: 100,
                    last_updated: '2025-11-15T12:00:00Z'
                }
            ],
            items: {
                '$ref': '#/components/schemas/TiktokPost'
            },
            title: 'Posts',
            type: 'array'
        }
    },
    required: ['channels', 'posts'],
    title: 'BackendState',
    type: 'object'
} as const;

export const BackendStateActionAddChannelSchema = {
    properties: {
        channel: {
            '$ref': '#/components/schemas/CreateTiktokChannel'
        }
    },
    required: ['channel'],
    title: 'BackendStateActionAddChannel',
    type: 'object'
} as const;

export const CreateTiktokChannelSchema = {
    properties: {
        id: {
            description: 'id as a internal integer',
            title: 'Id',
            type: 'string'
        },
        nickname: {
            description: 'To show as UI',
            title: 'Nickname',
            type: 'string'
        },
        handle: {
            description: 'In the twitter @handle format',
            title: 'Handle',
            type: 'string'
        },
        description: {
            description: 'Profile description',
            title: 'Description',
            type: 'string'
        },
        avatar_url: {
            description: 'Profile avatar URL',
            title: 'Avatar Url',
            type: 'string'
        },
        stats: {
            '$ref': '#/components/schemas/TiktokUserStats',
            description: 'User aggregated stats'
        }
    },
    required: ['id', 'nickname', 'handle', 'description', 'avatar_url', 'stats'],
    title: 'TiktokChannel',
    type: 'object'
} as const;

export const TiktokChannelSchema = {
    properties: {
        id: {
            description: 'id as a internal integer',
            title: 'Id',
            type: 'string'
        },
        nickname: {
            description: 'To show as UI',
            title: 'Nickname',
            type: 'string'
        },
        handle: {
            description: 'In the twitter @handle format',
            title: 'Handle',
            type: 'string'
        },
        description: {
            description: 'Profile description',
            title: 'Description',
            type: 'string'
        },
        avatar_url: {
            description: 'Profile avatar URL',
            title: 'Avatar Url',
            type: 'string'
        },
        stats: {
            '$ref': '#/components/schemas/TiktokUserStats',
            description: 'User aggregated stats'
        }
    },
    required: ['id', 'nickname', 'handle', 'description', 'avatar_url', 'stats'],
    title: 'TiktokChannel',
    type: 'object'
} as const;

export const TiktokPostSchema = {
    properties: {
        id: {
            title: 'Id',
            type: 'string'
        },
        title: {
            title: 'Title',
            type: 'string'
        },
        description: {
            title: 'Description',
            type: 'string'
        },
        url: {
            title: 'Url',
            type: 'string'
        },
        views: {
            title: 'Views',
            type: 'integer'
        },
        last_updated: {
            format: 'date-time',
            title: 'Last Updated',
            type: 'string'
        }
    },
    required: ['id', 'title', 'description', 'url', 'views', 'last_updated'],
    title: 'TiktokPost',
    type: 'object'
} as const;

export const TiktokUserStatsSchema = {
    properties: {
        follower_count: {
            title: 'Follower Count',
            type: 'integer'
        },
        following_count: {
            title: 'Following Count',
            type: 'integer'
        },
        heart_count: {
            title: 'Heart Count',
            type: 'integer'
        },
        video_count: {
            title: 'Video Count',
            type: 'integer'
        }
    },
    required: ['follower_count', 'following_count', 'heart_count', 'video_count'],
    title: 'TiktokUserStats',
    type: 'object'
} as const;
