// This file is auto-generated by @hey-api/openapi-ts

export const BackendStateActionsKeysSchema = {
    description: 'Lists all action keys as enum values',
    type: 'string',
    enum: ['add_channel'],
    title: 'BackendStateActionsKeys'
} as const;

export const BackendStateActionsParamsSchema = {
    description: 'Maps each action keys to its parameters',
    properties: {
        add_channel: {
            '$ref': '#/components/schemas/BackendStateActionAddChannel'
        }
    },
    required: ['add_channel'],
    title: 'BackendStateActionsParams',
    type: 'object'
} as const;

export const BackendStateTasksKeysSchema = {
    description: 'Lists all task keys as enum values',
    type: 'string',
    enum: [],
    title: 'BackendStateTasksKeys'
} as const;

export const BackendStateTasksParamsSchema = {
    description: 'Maps each task key to its parameters',
    properties: {},
    required: [],
    title: 'BackendStateTasksParams',
    type: 'object'
} as const;

export const BackendStateSchema = {
    properties: {
        channels: {
            default: [],
            items: {
                '$ref': '#/components/schemas/TiktokChannel'
            },
            title: 'Channels',
            type: 'array'
        },
        postsByChannelId: {
            additionalProperties: {
                items: {
                    '$ref': '#/components/schemas/TiktokPost'
                },
                type: 'array'
            },
            default: {},
            title: 'Postsbychannelid',
            type: 'object'
        },
        postEvaluations: {
            additionalProperties: {
                '$ref': '#/components/schemas/TiktokPostEvaluation'
            },
            default: {
                1: {
                    date_evaluated: null,
                    estimated_ctr: 0.2,
                    evaluation_text: null,
                    id: '1',
                    post_type: 'demo',
                    product_mentioned: true,
                    prominence_of_product: 'high',
                    target_group_fit: 'high'
                }
            },
            description: 'Post evaluations by post id',
            title: 'Postevaluations',
            type: 'object'
        },
        postPayouts: {
            additionalProperties: {
                items: {
                    '$ref': '#/components/schemas/Payout'
                },
                type: 'array'
            },
            default: {
                1: [
                    {
                        bonus_reason: 'The post is well-crafted and engaging',
                        chat_between_agent_and_creator: {
                            chat_history: [
                                {
                                    content: 'Hello, how are you?',
                                    role: 'payout_agent',
                                    timestamp: '2025-11-15T16:07:39.151057'
                                },
                                {
                                    content: "I'm good, thank you!",
                                    role: 'creator',
                                    timestamp: '2025-11-15T16:07:39.151064'
                                }
                            ]
                        },
                        date_paid: '2025-11-15T16:07:39.151067',
                        determined_base_payout: 100,
                        determined_bonus: 30,
                        determined_final_payout: 120,
                        determined_penalty: 10,
                        determined_price_per_1k: 1,
                        number_of_views: 100,
                        penalty_reason: 'The post is not relevant to the target group'
                    }
                ]
            },
            description: 'Payout history by post id',
            title: 'Postpayouts',
            type: 'object'
        }
    },
    required: ['channels', 'postsByChannelId', 'postEvaluations', 'postPayouts'],
    title: 'BackendState',
    type: 'object'
} as const;

export const BackendStateActionAddChannelSchema = {
    properties: {
        channel: {
            '$ref': '#/components/schemas/CreateTiktokChannel'
        }
    },
    required: ['channel'],
    title: 'BackendStateActionAddChannel',
    type: 'object'
} as const;

export const ChatBetweenAgentAndCreatorSchema = {
    properties: {
        chat_history: {
            default: [],
            items: {
                '$ref': '#/components/schemas/ChatMessage'
            },
            title: 'Chat History',
            type: 'array'
        }
    },
    required: ['chat_history'],
    title: 'ChatBetweenAgentAndCreator',
    type: 'object'
} as const;

export const ChatMessageSchema = {
    properties: {
        role: {
            description: 'Role of the message sender',
            enum: ['payout_agent', 'creator'],
            title: 'Role',
            type: 'string'
        },
        content: {
            description: 'Content of the message',
            title: 'Content',
            type: 'string'
        },
        timestamp: {
            description: 'Timestamp of the message',
            format: 'date-time',
            title: 'Timestamp',
            type: 'string'
        }
    },
    required: ['role', 'content', 'timestamp'],
    title: 'ChatMessage',
    type: 'object'
} as const;

export const CreateTiktokChannelSchema = {
    properties: {
        id: {
            description: 'id as a internal integer',
            title: 'Id',
            type: 'string'
        },
        nickname: {
            description: 'To show as UI',
            title: 'Nickname',
            type: 'string'
        },
        handle: {
            description: 'In the twitter @handle format',
            title: 'Handle',
            type: 'string'
        },
        description: {
            description: 'Profile description',
            title: 'Description',
            type: 'string'
        },
        avatar_url: {
            description: 'Profile avatar URL',
            title: 'Avatar Url',
            type: 'string'
        },
        stats: {
            '$ref': '#/components/schemas/TiktokUserStats',
            description: 'User aggregated stats'
        }
    },
    required: ['id', 'nickname', 'handle', 'description', 'avatar_url', 'stats'],
    title: 'TiktokChannel',
    type: 'object'
} as const;

export const PayoutSchema = {
    properties: {
        chat_between_agent_and_creator: {
            '$ref': '#/components/schemas/ChatBetweenAgentAndCreator',
            description: 'social context between the agent and the creator'
        },
        number_of_views: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Number of views of the post',
            title: 'Number Of Views'
        },
        determined_price_per_1k: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Determined price per 1K views, based on the post evaluation',
            title: 'Determined Price Per 1K'
        },
        determined_base_payout: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Determined base payout for the post, in USDC',
            title: 'Determined Base Payout'
        },
        determined_penalty: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Determined penalty for the post, in USDC, so value of x means the payout is reduced by x USDC, always non-negative',
            title: 'Determined Penalty'
        },
        penalty_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Reason for the penalty',
            title: 'Penalty Reason'
        },
        determined_bonus: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Determined bonus for the post, in USDC, so value of x means the payout is increased by x USDC, always non-negative',
            title: 'Determined Bonus'
        },
        bonus_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Reason for the bonus',
            title: 'Bonus Reason'
        },
        determined_final_payout: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Determined final payout based on all factors, in USDC',
            title: 'Determined Final Payout'
        },
        date_paid: {
            description: 'Date paid',
            format: 'date-time',
            title: 'Date Paid',
            type: 'string'
        }
    },
    required: ['chat_between_agent_and_creator', 'number_of_views', 'determined_price_per_1k', 'determined_base_payout', 'determined_penalty', 'penalty_reason', 'determined_bonus', 'bonus_reason', 'determined_final_payout', 'date_paid'],
    title: 'Payout',
    type: 'object'
} as const;

export const TiktokChannelSchema = {
    properties: {
        id: {
            description: 'id as a internal integer',
            title: 'Id',
            type: 'string'
        },
        nickname: {
            description: 'To show as UI',
            title: 'Nickname',
            type: 'string'
        },
        handle: {
            description: 'In the twitter @handle format',
            title: 'Handle',
            type: 'string'
        },
        description: {
            description: 'Profile description',
            title: 'Description',
            type: 'string'
        },
        avatar_url: {
            description: 'Profile avatar URL',
            title: 'Avatar Url',
            type: 'string'
        },
        stats: {
            '$ref': '#/components/schemas/TiktokUserStats',
            description: 'User aggregated stats'
        }
    },
    required: ['id', 'nickname', 'handle', 'description', 'avatar_url', 'stats'],
    title: 'TiktokChannel',
    type: 'object'
} as const;

export const TiktokPostSchema = {
    properties: {
        id: {
            description: 'id as a internal integer',
            title: 'Id',
            type: 'string'
        },
        date_posted: {
            description: 'Date posted',
            format: 'date-time',
            title: 'Date Posted',
            type: 'string'
        },
        description: {
            description: 'Post description',
            title: 'Description',
            type: 'string'
        },
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            description: 'Post URL, if available',
            title: 'Url'
        },
        dynamic_cover_url: {
            description: 'Dynamic cover URL',
            title: 'Dynamic Cover Url',
            type: 'string'
        },
        stats: {
            '$ref': '#/components/schemas/TiktokPostStats',
            description: 'Post aggregated stats'
        }
    },
    required: ['id', 'date_posted', 'description', 'url', 'dynamic_cover_url', 'stats'],
    title: 'TiktokPost',
    type: 'object'
} as const;

export const TiktokPostEvaluationSchema = {
    properties: {
        id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'id as a internal integer',
            title: 'Id'
        },
        product_mentioned: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Whether the product is mentioned in the post',
            title: 'Product Mentioned'
        },
        prominence_of_product: {
            anyOf: [
                {
                    enum: ['high', 'medium', 'low'],
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'How prominent the product is in the post',
            title: 'Prominence Of Product'
        },
        target_group_fit: {
            anyOf: [
                {
                    enum: ['high', 'medium', 'low'],
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'How well the post fits the target group',
            title: 'Target Group Fit'
        },
        post_type: {
            anyOf: [
                {
                    enum: ['demo', 'review', 'product recommendation', 'trend', 'other'],
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Type of post',
            title: 'Post Type'
        },
        estimated_ctr: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Estimated CTR (typically around 0.2% to 5%)',
            title: 'Estimated Ctr'
        },
        date_evaluated: {
            anyOf: [
                {
                    format: 'date-time',
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Date evaluated',
            title: 'Date Evaluated'
        },
        evaluation_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            default: null,
            description: 'Evaluation',
            title: 'Evaluation Text'
        }
    },
    required: ['id', 'product_mentioned', 'prominence_of_product', 'target_group_fit', 'post_type', 'estimated_ctr', 'date_evaluated', 'evaluation_text'],
    title: 'TiktokPostEvaluation',
    type: 'object'
} as const;

export const TiktokPostStatsSchema = {
    properties: {
        play_count: {
            description: 'number of views/plays',
            title: 'Play Count',
            type: 'integer'
        },
        like_count: {
            description: 'number of likes',
            title: 'Like Count',
            type: 'integer'
        },
        comment_count: {
            description: 'number of comments',
            title: 'Comment Count',
            type: 'integer'
        },
        share_count: {
            description: 'number of shares',
            title: 'Share Count',
            type: 'integer'
        },
        save_count: {
            description: 'number of saves/bookmarks',
            title: 'Save Count',
            type: 'integer'
        }
    },
    required: ['play_count', 'like_count', 'comment_count', 'share_count', 'save_count'],
    title: 'TiktokPostStats',
    type: 'object'
} as const;

export const TiktokUserStatsSchema = {
    properties: {
        follower_count: {
            title: 'Follower Count',
            type: 'integer'
        },
        following_count: {
            title: 'Following Count',
            type: 'integer'
        },
        heart_count: {
            title: 'Heart Count',
            type: 'integer'
        },
        video_count: {
            title: 'Video Count',
            type: 'integer'
        }
    },
    required: ['follower_count', 'following_count', 'heart_count', 'video_count'],
    title: 'TiktokUserStats',
    type: 'object'
} as const;
