// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * HelloSyncActionsKeys
 *
 * Lists all action keys as enum values
 */
export const HelloSyncActionsKeys = {
    setMessage: 'set_message'
} as const;

/**
 * HelloSyncActionsKeys
 *
 * Lists all action keys as enum values
 */
export type HelloSyncActionsKeys = typeof HelloSyncActionsKeys[keyof typeof HelloSyncActionsKeys];

/**
 * HelloSyncActionsParams
 *
 * Maps each action keys to its parameters
 */
export type HelloSyncActionsParams = {
    set_message: HelloSyncActionSetMessage;
};

/**
 * HelloSyncTasksKeys
 *
 * Lists all task keys as enum values
 */
export const HelloSyncTasksKeys = {} as const;

/**
 * HelloSyncTasksKeys
 *
 * Lists all task keys as enum values
 */
export type HelloSyncTasksKeys = typeof HelloSyncTasksKeys[keyof typeof HelloSyncTasksKeys];

/**
 * HelloSyncTasksParams
 *
 * Maps each task key to its parameters
 */
export type HelloSyncTasksParams = {
    [key: string]: unknown;
};

/**
 * HelloSync
 */
export type HelloSync = {
    /**
     * Message
     */
    message: string;
};

/**
 * HelloSyncActionSetMessage
 */
export type HelloSyncActionSetMessage = {
    /**
     * Message
     */
    message: string;
};
