// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * BackendStateActionsKeys
 *
 * Lists all action keys as enum values
 */
export const BackendStateActionsKeys = {
    addChannel: 'add_channel'
} as const;

/**
 * BackendStateActionsKeys
 *
 * Lists all action keys as enum values
 */
export type BackendStateActionsKeys = typeof BackendStateActionsKeys[keyof typeof BackendStateActionsKeys];

/**
 * BackendStateActionsParams
 *
 * Maps each action keys to its parameters
 */
export type BackendStateActionsParams = {
    add_channel: BackendStateActionAddChannel;
};

/**
 * BackendStateTasksKeys
 *
 * Lists all task keys as enum values
 */
export const BackendStateTasksKeys = {} as const;

/**
 * BackendStateTasksKeys
 *
 * Lists all task keys as enum values
 */
export type BackendStateTasksKeys = typeof BackendStateTasksKeys[keyof typeof BackendStateTasksKeys];

/**
 * BackendStateTasksParams
 *
 * Maps each task key to its parameters
 */
export type BackendStateTasksParams = {
    [key: string]: unknown;
};

/**
 * BackendState
 */
export type BackendState = {
    /**
     * Channels
     */
    channels: Array<TiktokChannel>;
    /**
     * Postsbychannelid
     */
    postsByChannelId: {
        [key: string]: Array<TiktokPost>;
    };
};

/**
 * BackendStateActionAddChannel
 */
export type BackendStateActionAddChannel = {
    channel: CreateTiktokChannel;
};

/**
 * TiktokChannel
 */
export type CreateTiktokChannel = {
    /**
     * Id
     *
     * id as a internal integer
     */
    id: string;
    /**
     * Nickname
     *
     * To show as UI
     */
    nickname: string;
    /**
     * Handle
     *
     * In the twitter @handle format
     */
    handle: string;
    /**
     * Description
     *
     * Profile description
     */
    description: string;
    /**
     * Avatar Url
     *
     * Profile avatar URL
     */
    avatar_url: string;
    /**
     * User aggregated stats
     */
    stats: TiktokUserStats;
};

/**
 * TiktokChannel
 */
export type TiktokChannel = {
    /**
     * Id
     *
     * id as a internal integer
     */
    id: string;
    /**
     * Nickname
     *
     * To show as UI
     */
    nickname: string;
    /**
     * Handle
     *
     * In the twitter @handle format
     */
    handle: string;
    /**
     * Description
     *
     * Profile description
     */
    description: string;
    /**
     * Avatar Url
     *
     * Profile avatar URL
     */
    avatar_url: string;
    /**
     * User aggregated stats
     */
    stats: TiktokUserStats;
};

/**
 * TiktokPost
 */
export type TiktokPost = {
    /**
     * Id
     *
     * id as a internal integer
     */
    id: string;
    /**
     * Date Posted
     *
     * Date posted
     */
    date_posted: string;
    /**
     * Description
     *
     * Post description
     */
    description: string;
    /**
     * Url
     *
     * Post URL, if available
     */
    url: string | null;
    /**
     * Dynamic Cover Url
     *
     * Dynamic cover URL
     */
    dynamic_cover_url: string;
    /**
     * Post aggregated stats
     */
    stats: TiktokPostStats;
};

/**
 * TiktokPostStats
 */
export type TiktokPostStats = {
    /**
     * Play Count
     *
     * number of views/plays
     */
    play_count: number;
    /**
     * Like Count
     *
     * number of likes
     */
    like_count: number;
    /**
     * Comment Count
     *
     * number of comments
     */
    comment_count: number;
    /**
     * Share Count
     *
     * number of shares
     */
    share_count: number;
    /**
     * Save Count
     *
     * number of saves/bookmarks
     */
    save_count: number;
};

/**
 * TiktokUserStats
 */
export type TiktokUserStats = {
    /**
     * Follower Count
     */
    follower_count: number;
    /**
     * Following Count
     */
    following_count: number;
    /**
     * Heart Count
     */
    heart_count: number;
    /**
     * Video Count
     */
    video_count: number;
};
