// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

/**
 * BackendStateActionsKeys
 *
 * Lists all action keys as enum values
 */
export const zBackendStateActionsKeys = z.enum([
    'add_channel'
]);

/**
 * BackendStateTasksKeys
 *
 * Lists all task keys as enum values
 */
export const zBackendStateTasksKeys = z.unknown();

/**
 * BackendStateTasksParams
 *
 * Maps each task key to its parameters
 */
export const zBackendStateTasksParams = z.record(z.string(), z.unknown());

/**
 * TiktokPostStats
 */
export const zTiktokPostStats = z.object({
    play_count: z.int(),
    like_count: z.int(),
    comment_count: z.int(),
    share_count: z.int(),
    save_count: z.int()
});

/**
 * TiktokPost
 */
export const zTiktokPost = z.object({
    id: z.string(),
    description: z.string(),
    url: z.union([
        z.string(),
        z.null()
    ]),
    stats: zTiktokPostStats
});

/**
 * TiktokUserStats
 */
export const zTiktokUserStats = z.object({
    follower_count: z.int(),
    following_count: z.int(),
    heart_count: z.int(),
    video_count: z.int()
});

/**
 * TiktokChannel
 */
export const zCreateTiktokChannel = z.object({
    id: z.string(),
    nickname: z.string(),
    handle: z.string(),
    description: z.string(),
    avatar_url: z.string(),
    stats: zTiktokUserStats
});

/**
 * BackendStateActionAddChannel
 */
export const zBackendStateActionAddChannel = z.object({
    channel: zCreateTiktokChannel
});

/**
 * BackendStateActionsParams
 *
 * Maps each action keys to its parameters
 */
export const zBackendStateActionsParams = z.object({
    add_channel: zBackendStateActionAddChannel
});

/**
 * TiktokChannel
 */
export const zTiktokChannel = z.object({
    id: z.string(),
    nickname: z.string(),
    handle: z.string(),
    description: z.string(),
    avatar_url: z.string(),
    stats: zTiktokUserStats
});

/**
 * BackendState
 */
export const zBackendState = z.object({
    channels: z.array(zTiktokChannel).default([
        {
            id: '123',
            nickname: 'Channel 1',
            handle: 'channel1',
            description: 'Description 1',
            avatar_url: 'https://p16-common-sign.tiktokcdn-us.com/tos-maliva-avt-0068/f611aa99e7db2b1f81ce145c7b063078~tplv-tiktokx-cropcenter:1080:1080.jpeg?dr=9640&refresh_token=cb4d1315&x-expires=1763413200&x-signature=tkYPKZGSeWlK%2BYxuvzFyhzRxR%2FI%3D&t=4d5b0474&ps=13740610&shp=a5d48078&shcp=81f88b70&idc=useast8',
            stats: {
                follower_count: 100,
                following_count: 100,
                heart_count: 100,
                video_count: 100
            }
        }
    ]),
    posts: z.array(zTiktokPost).default([
        {
            id: '1',
            description: 'post description',
            url: null,
            stats: {
                comment_count: 32,
                like_count: 100,
                play_count: 1234,
                save_count: 450,
                share_count: 340
            }
        }
    ])
});
